name: TV Card Custom
description: TV Remote Card Custom Edit
type: lovelace
keywords:
  - tvcard
  - remote
  - tv
  - television
author:
  name: mar_robHD
license: Apache License, Version 2.0
files:
  - tv-card.js
  - tv-card-editor.js
